FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y docker.io wget unzip
RUN wget https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip && unzip terraform_1.8.0_linux_amd64.zip && mv terraform /usr/local/bin/ && rm terraform_1.8.0_linux_amd64.zip
RUN usermod -aG docker jenkins
USER jenkins
